import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import YandexMap from "@/components/map/YandexMap";
import { gql } from "@apollo/client/core";
import { useQuery } from "@apollo/client";
import Test from "@/components/screens/test";
import ClientOnly from "@/graphql/clientOnly";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <YandexMap></YandexMap>
        <ClientOnly>
          <Test></Test>
        </ClientOnly>
      </main>
    </>
  );
}
